# Generated by Django 5.2.1 on 2025-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('template', 'Template'), ('media', 'Media'), ('file', 'File')], default='note', max_length=50),
        ),
    ]
