# Generated by Django 5.2.3 on 2025-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_vector_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entity',
            new_name='api_entity_type_a8c9e9_idx',
            old_name='api_entity_type_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='api_entity_parent__5240a8_idx',
            old_name='api_entity_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='api_entity_updated_68438c_idx',
            old_name='api_entity_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='api_entity_embeddi_ba3402_idx',
            old_name='api_entity_embedding_updated_at_idx',
        ),
    ]
