# Generated by Django 5.2.3 on 2025-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_api_entity_type_idx_api_entity_type_a8c9e9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('template', 'Template'), ('media', 'Media'), ('view', 'View'), ('widget', 'Widget'), ('kanban', 'Kanban'), ('calendar', 'Calendar'), ('canvas', 'Canvas'), ('ai_chat_history', 'AI Chat History')], default='note', max_length=50),
        ),
    ]
