# Generated by Django 5.2.3 on 2025-06-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_ai_chat_history_entity_type'),
        ('api', '0007_add_ai_chat_history_entity_type'),
    ]

    operations = [
    ]
