# Generated by Django 5.2.3 on 2025-06-16 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250611_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entity')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entities', through='api.EntityTag', to='api.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='api_tag_name_38f172_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent'], name='api_tag_parent__616cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='entitytag',
            index=models.Index(fields=['entity'], name='api_entityt_entity__67c04a_idx'),
        ),
        migrations.AddIndex(
            model_name='entitytag',
            index=models.Index(fields=['tag'], name='api_entityt_tag_id_d50ce1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitytag',
            unique_together={('entity', 'tag')},
        ),
    ]
