# Generated by Django 5.2.3 on 2025-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tag_entitytag_entity_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Custom metadata and properties stored as JSON'),
        ),
    ]
