# Generated by Augment Agent to add sync fields for offline-first
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_entity_metadata'),
    ]

    operations = [
        # Entity sync fields
        migrations.AddField(
            model_name='entity',
            name='rev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='server_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='deleted_at',
            field=models.DateTimeField(null=True, blank=True),
        ),

        # Tag sync fields
        migrations.AddField(
            model_name='tag',
            name='rev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='server_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]

