# Generated by Django 5.2.7 on 2025-11-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='rev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='server_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='server_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='server_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['server_updated_at'], name='api_entity_server__56dbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['deleted'], name='api_entity_deleted_695cca_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['server_updated_at'], name='api_tag_server__134d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['deleted'], name='api_tag_deleted_ea6fc1_idx'),
        ),
    ]
