# Generated by Django 5.2.8 on 2025-11-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_theme_deleted_theme_deleted_at_theme_rev_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='theme',
            name='type',
        ),
    ]
