services:
    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=souzou
            - POSTGRES_USER=postgres        # Username for your postgres datbase
            - POSTGRES_PASSWORD=postgres    # Password for your postgres user
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        hostname: postgresql
        networks:
            - app
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app
    django:
        stdin_open: true
        build: 
            context: "django"
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8000:8000'
        volumes:
            - ./django:/app
        hostname: django
        networks:
            - app
        env_file: ".env"
        depends_on:
            - db
    frontend:
        stdin_open: true
        build: 
            context: "frontend"
            dockerfile: Dockerfile
        volumes:
            - ./frontend/:/app
        ports:
            - 5173:5173
        environment:
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
        restart: always
        networks:
            - app
networks:
    app:
        driver: bridge